services:
  backend:
    build: ./backend
    container_name: meu_bot_backend
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - CHROME_HEADLESS=True
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: meu_bot_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
